const window = require('./index.js');
globalThis.Document    = window.Document;
globalThis.Node        = window.Node;
globalThis.Element     = window.Element;
globalThis.Comment     = window.Comment;
globalThis.Text        = window.Text;
globalThis.document    = window.document;
globalThis.Event       = window.Event;
globalThis.CustomEvent = window.CustomEvent;
